[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"

[config]
proxy = "https://github.com/roblox/rotriever-proxy-index"

[dependencies]
Roact = "github.com/roblox/roact@1.3.1"
Rodux = "github.com/roblox/rodux@1.0"
RoactRodux = "github.com/roblox/roact-rodux@0.2"
RoactNavigation = "github.com/roblox/roact-navigation@0.4.1"
Cryo = "github.com/roblox/cryo@1.0"
Dash = "github.com/roblox/dash@0.1"
LuaChatDeps = { git = "https://github.com/Roblox/lua-chat-deps" }
LuaSocialLibrariesDeps = { git = "https://github.com/Roblox/lua-social-libraries-deps" }
PremiumUpsellDeps = { git = "https://github.com/Roblox/premium-upsell-deps" }
AvatarExperienceDeps = { git = "https://github.com/Roblox/avatar-experience-deps" }
LuaProfileDeps = { git = "https://github.com/Roblox/lua-profile", rev = "master" }
PurchasePromptDeps = { git = "https://github.com/Roblox/purchase-prompt-deps" }
IAPExperience = { git = "https://github.com/Roblox/IAPExperience", rev = "master" }
UIBlox = { git = "https://github.com/Roblox/uiblox", rev = "master" }
Thumbnailing = { git = "https://github.com/Roblox/Thumbnailing", rev = "main" }
Otter = "github.com/roblox/otter@0.1.3"
t = "github.com/roblox/t@1.0"
enumerate = "github.com/roblox/enumerate@1.0.0"
PolicyProvider = { git = "https://github.com/Roblox/lua-roact-policy-provider", rev = "master" }
Lumberyak = { git = "https://github.com/Roblox/lumberyak" }
StringUtilities = "github.com/Roblox/string-utilities@1.0.0"
UrlBuilder = { git = "https://github.com/Roblox/url-builder", rev = "master" }
FitFrame = "github.com/roblox/roact-fit-components@1.4.0"
ExperienceChat = { git = "https://github.com/Roblox/lua-experience-chat", rev = "v0.0.3" }
GetFFlagLegacyRoactUpgradeFlag = { git = "https://github.com/Roblox/roact-17-upgrade", rev = "main", package = "GetFFlagLegacyRoactUpgradeFlag" }

# The following packages were ported from AppTempCommon
Promise = { git = "https://github.com/Roblox/lua-promise" }
Result = { git = "https://github.com/Roblox/lua-result" }
tutils = { git = "https://github.com/Roblox/tutils" }

InGameMenuDependencies = { git = "https://github.com/Roblox/in-game-menu-dependencies", rev = "master" }

RoactGamepad = "github.com/roblox/roact-gamepad@0.4.6"

[dev_dependencies]
JestGlobals = { git = "https://github.com/roblox/jest-roblox", rev = "v2.1.4" }
Rhodium = "github.com/roblox/rhodium@0.2.6"

# Dependencies for the Roact17 inspector
ReactDevtoolsExtensions = { git = "https://github.com/roblox/roact-alignment", package = "ReactDevtoolsExtensions", rev="v17.0.1-rc.7" }
DeveloperTools = "github.com/Roblox/developer-tools@0.2.2"

# Patch all dependencies upon rodux to the flagged indireciton package, which
# will ensure that we always use only one rodux version
[config.patch."https://github.com/roblox/rodux"]
Rodux = { git = "https://github.com/roblox/rodux", rev = "v3.0.0" }

[config.patch_git."https://github.com/Roblox/lua-promise"]
Promise = "github.com/Roblox/roblox-lua-promise@3.2.1"

[config.patch."github.com/evaera/roblox-lua-promise"]
Promise = "github.com/Roblox/roblox-lua-promise@3.2.1"

[config.patch."https://github.com/roblox/roact-navigation"]
RoactNavigation = { git = "https://github.com/roblox/roact-navigation", rev = "v0.4.1-patch3" }

# Roact 17 - Patch in flagged proxy for roact, roact-rodux, infinite-scroller, and gamepad
[config.patch."github.com/roblox/roact"]
Roact = { git = "https://github.com/Roblox/roact-17-upgrade", rev = "main", package = "RoactProxy" }

[config.patch."github.com/roblox/roact-rodux"]
RoactRodux = { git = "https://github.com/Roblox/roact-17-upgrade", rev = "main", package = "RoactRoduxProxy" }

[config.patch."github.com/roblox/infinite-scroller"]
InfiniteScroller = { git = "https://github.com/Roblox/roact-17-upgrade", rev = "main", package = "InfiniteScrollerProxy" }

[config.patch."github.com/roblox/roact-gamepad"]
RoactGamepad = { git = "https://github.com/Roblox/roact-17-upgrade", rev = "main", package = "RoactGamepadProxy" }
