--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["InfiniteScroller-ff42b2c3-b387832f"]["InfiniteScroller"])

return Package
