--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["roblox_rodux-users-298a3b93-243ca422"]["rodux-users"])

return Package
