--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["roblox_networking-friends-1bbc8c04-1a482d38"]["networking-friends"])

return Package
