--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["rodux-networking-14620053-3c77c96c"]["rodux-networking"])

return Package
